import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          (),
        ]),
      ),
    );
  }
}

class  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: -3,
                child: Container(
                  width: 360,
                  height: 803,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 14,
                        top: 44,
                        child: Container(
                          width: 332,
                          height: 36,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 8,
                                top: 12,
                                child: Container(
                                  width: 16.45,
                                  height: 14,
                                  child: Stack(children: [
                                  ,
                                  ]),
                                ),
                              ),
                              Positioned(
                                left: 52,
                                top: 0,
                                child: SizedBox(
                                  width: 213,
                                  height: 30,
                                  child: Text(
                                    'Wellness Score',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF252C28),
                                      fontSize: 18,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 294.90,
                                top: 11,
                                child: Container(
                                  width: 1.70,
                                  height: 17,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 7,
                                        child: Container(
                                          width: 1.70,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 1,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: Color(0xFF29292D),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 1.70,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 1,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: Color(0xFF29292D),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 15,
                                        child: Container(
                                          width: 1.70,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 1,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: Color(0xFF29292D),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 112,
                        child: Container(
                          width: 223,
                          height: 50,
                          padding: const EdgeInsets.only(left: 6),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.end,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 244,
                                height: 66,
                                child: Text(
                                  'Self-Percepted stress Vs iWatch Output',
                                  style: TextStyle(
                                    color: Color(0xFF29292D),
                                    fontSize: 18,
                                    fontFamily: 'Raleway',
                                    fontWeight: FontWeight.w500,
                                    height: 30,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 733,
                        child: Container(
                          width: 360,
                          height: 70,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 360,
                                  height: 70,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                    boxShadow: [
                                      BoxShadow(
                                        color: Color(0x1E000000),
                                        blurRadius: 48,
                                        offset: Offset(0, 2),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 71,
                                top: 15,
                                child: Container(
                                  width: 221,
                                  height: 18,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 17,
                                          height: 17,
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 203,
                                        top: 0,
                                        child: Container(
                                          width: 18,
                                          height: 17,
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 360,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 321.33,
                                top: 17.33,
                                child: Container(
                                  width: 24.33,
                                  height: 11.33,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Opacity(
                                          opacity: 0.35,
                                          child: Container(
                                            width: 22,
                                            height: 11.33,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 0.50, color: Color(0xFF3C3C3C)),
                                                borderRadius: BorderRadius.circular(2.67),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 2,
                                        top: 2,
                                        child: Container(
                                          width: 18,
                                          height: 7.33,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFF29292D),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(1.33),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 303.36,
                                top: 17.33,
                                child: Container(
                                  width: 14.72,
                                  height: 11,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/15x11"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 282.24,
                                top: 17.67,
                                child: Container(
                                  width: 16.32,
                                  height: 10.67,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/16x11"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 3,
                                top: 7.33,
                                child: Container(
                                  width: 54,
                                  padding: const EdgeInsets.only(top: 7),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        width: 54,
                                        child: Text(
                                          '9:41',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Color(0xFF29292D),
                                            fontSize: 15,
                                            fontFamily: 'Raleway',
                                            fontWeight: FontWeight.w700,
                                            letterSpacing: -0.30,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 183,
                        child: Container(
                          width: 333,
                          height: 50,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 333,
                                  height: 50,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF2F2F2),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 25.88,
                                top: 18,
                                child: SizedBox(
                                  width: 39.68,
                                  child: Text(
                                    'Week 1',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFFACAAB5),
                                      fontSize: 10,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w500,
                                      letterSpacing: 1,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 89.72,
                                top: 6,
                                child: Container(
                                  width: 84.54,
                                  height: 38,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 84.54,
                                          height: 38,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(10),
                                            ),
                                            shadows: [
                                              BoxShadow(
                                                color: Color(0x0F000000),
                                                blurRadius: 5,
                                                offset: Offset(0, 4),
                                                spreadRadius: 0,
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 18.98,
                                        top: 12,
                                        child: SizedBox(
                                          width: 42.27,
                                          child: Text(
                                            'Week 2',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Color(0xFF6266EA),
                                              fontSize: 10,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w500,
                                              letterSpacing: 1,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 198.42,
                                top: 18,
                                child: SizedBox(
                                  width: 42.27,
                                  child: Text(
                                    'Week 3',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFFACAAB5),
                                      fontSize: 10,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w500,
                                      letterSpacing: 1,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 263.98,
                                top: 18,
                                child: SizedBox(
                                  width: 43.13,
                                  child: Text(
                                    'Week 4',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFFACAAB5),
                                      fontSize: 10,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w500,
                                      letterSpacing: 1,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 481,
                child: Text(
                  'Today',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 18,
                    fontFamily: 'Raleway',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 239.59,
                child: Container(
                  width: 316.50,
                  height: 219,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 6,
                        child: Container(width: 314.08, height: 212.14),
                      ),
                      Positioned(
                        left: 24,
                        top: 207,
                        child: Text(
                          'S',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 71.17,
                        top: 207,
                        child: Text(
                          'M',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 120.33,
                        top: 207,
                        child: Text(
                          'T',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 167.50,
                        top: 207,
                        child: Text(
                          'W',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 213.67,
                        top: 207,
                        child: Text(
                          'Th',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 264.83,
                        top: 207,
                        child: Text(
                          'F',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 300.06,
                        top: 207,
                        child: Text(
                          'Sat',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 11,
                        top: 193,
                        child: Text(
                          '0',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 145,
                        child: Text(
                          '25',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 97,
                        child: Text(
                          '50',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 49,
                        child: Text(
                          '75',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          '100',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFA3A3A3),
                            fontSize: 10,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 627,
                child: Container(
                  width: 303,
                  height: 82,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 303,
                          height: 82,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.5),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.50,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFF6266EA),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 18,
                        top: 27,
                        child: Text(
                          'Self Report',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 18,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 174,
                        top: 31,
                        child: Container(
                          width: 104,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.50,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFF6266EA),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 211,
                        top: 12,
                        child: Text(
                          'Low',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 18,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                            height: 58,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 523,
                child: Container(
                  width: 303,
                  height: 82,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 303,
                          height: 82,
                          decoration: ShapeDecoration(
                            color: Colors.white.withOpacity(0.5),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.50,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFFCADDF),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9,
                        top: 26,
                        child: Text(
                          'iWatch report',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 18,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 170,
                        top: 31,
                        child: Container(
                          width: 104,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.50,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFFCADDF),
                              ),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 212,
                        top: 12,
                        child: Text(
                          'Low',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 18,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                            height: 58,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

