import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          A(),
        ]),
      ),
    );
  }
}

class A extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: 360,
                height: 800,
                decoration: BoxDecoration(color: Colors.white),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: 360,
                      height: 44,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 321.33,
                            top: 17.33,
                            child: Container(
                              width: 24.33,
                              height: 11.33,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Opacity(
                                      opacity: 0.35,
                                      child: Container(
                                        width: 22,
                                        height: 11.33,
                                        decoration: ShapeDecoration(
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 0.50, color: Color(0xFF3C3C3C)),
                                            borderRadius: BorderRadius.circular(2.67),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 2,
                                    top: 2,
                                    child: Container(
                                      width: 18,
                                      height: 7.33,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFF29292D),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(1.33),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 303.36,
                            top: 17.33,
                            child: Container(
                              width: 14.72,
                              height: 11,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/15x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                          ),
                          Positioned(
                            left: 282.24,
                            top: 17.67,
                            child: Container(
                              width: 16.32,
                              height: 10.67,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/16x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                          ),
                          Positioned(
                            left: 3,
                            top: 7.33,
                            child: Container(
                              width: 54,
                              padding: const EdgeInsets.only(top: 7),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  SizedBox(
                                    width: 54,
                                    child: Text(
                                      '9:41',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF29292D),
                                        fontSize: 15,
                                        fontFamily: 'Raleway',
                                        fontWeight: FontWeight.w700,
                                        letterSpacing: -0.30,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 360,
                      height: 800,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.00, -1.00),
                          end: Alignment(0, 1),
                          colors: [Color(0xFF6266EA), Color(0xFF050CE4), Color(0x7D8007B8), Color(0x00CE62EA)],
                        ),
                      ),
                    ),
                    Container(
                      width: 233.13,
                      height: 800,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 0,
                            top: 0,
                            child: Container(
                              width: 219,
                              height: 800,
                              decoration: ShapeDecoration(
                                color: Color(0xFF6266EA),
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(width: 0.50, color: Color(0xFF979797)),
                                ),
                              ),
                            ),
                          ),
                          Positioned(
                            left: 21,
                            top: 0,
                            child: Container(
                              width: 212.13,
                              height: 555,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 13,
                                    top: 494,
                                    child: Container(
                                      width: 149.39,
                                      height: 61,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 17,
                                            child: Container(
                                              width: 17,
                                              height: 17,
                                              decoration: ShapeDecoration(
                                                image: DecorationImage(
                                                  image: NetworkImage("https://via.placeholder.com/17x17"),
                                                  fit: BoxFit.fill,
                                                ),
                                                shape: RoundedRectangleBorder(
                                                  side: BorderSide(
                                                    width: 0.25,
                                                    strokeAlign: BorderSide.strokeAlignCenter,
                                                    color: Colors.white,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 32,
                                            top: 0,
                                            child: SizedBox(
                                              width: 117.39,
                                              height: 61,
                                              child: Text(
                                                'Sign Out',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 18,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w400,
                                                  height: 58,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 12,
                                    top: 436,
                                    child: Container(
                                      width: 173,
                                      height: 61,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 19,
                                            child: Container(
                                              width: 17,
                                              height: 17,
                                              child: Stack(children: [
                                              ,
                                              ]),
                                            ),
                                          ),
                                          Positioned(
                                            left: 33,
                                            top: 0,
                                            child: SizedBox(
                                              width: 140,
                                              height: 61,
                                              child: Text(
                                                'Wellness Score',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 18,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w400,
                                                  height: 58,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 12,
                                    top: 319,
                                    child: Container(
                                      width: 149.52,
                                      height: 61,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 33,
                                            top: 0,
                                            child: SizedBox(
                                              width: 116.52,
                                              height: 61,
                                              child: Text(
                                                'Check-In',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 18,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w400,
                                                  height: 58,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 12,
                                    top: 255,
                                    child: Container(
                                      width: 129.52,
                                      height: 61,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 18,
                                            child: Container(
                                              width: 17,
                                              height: 17,
                                              child: Stack(children: [
                                              ,
                                              ]),
                                            ),
                                          ),
                                          Positioned(
                                            left: 33,
                                            top: 0,
                                            child: SizedBox(
                                              width: 96.52,
                                              height: 61,
                                              child: Text(
                                                'Home',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 18,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w400,
                                                  height: 58,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 17,
                                    top: 152,
                                    child: Container(
                                      width: 195.13,
                                      height: 94,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: SizedBox(
                                              width: 189.16,
                                              height: 87.99,
                                              child: Text(
                                                'Emma Mabel',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 18,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w600,
                                                  height: 68,
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 1.65,
                                            top: 39.65,
                                            child: SizedBox(
                                              width: 193.48,
                                              height: 54.35,
                                              child: Text(
                                                'Houghton, MI',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 16,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w400,
                                                  height: 42,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 19,
                                    top: 66,
                                    child: Container(
                                      width: 104,
                                      height: 102,
                                      decoration: ShapeDecoration(
                                        image: DecorationImage(
                                          image: NetworkImage("https://via.placeholder.com/104x102"),
                                          fit: BoxFit.fill,
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(59.63),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: SizedBox(
                                      width: 67,
                                      height: 82,
                                      child: Text(
                                        'X',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 16,
                                          fontFamily: 'Raleway',
                                          fontWeight: FontWeight.w657,
                                          height: 32,
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 7,
                                    top: 376,
                                    child: Container(
                                      width: 154.52,
                                      height: 61,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 38,
                                            top: 0,
                                            child: SizedBox(
                                              width: 116.52,
                                              height: 61,
                                              child: Text(
                                                'iWatch',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 18,
                                                  fontFamily: 'Raleway',
                                                  fontWeight: FontWeight.w400,
                                                  height: 58,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 360,
                      height: 749,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 0,
                            top: 679,
                            child: Container(
                              width: 360,
                              height: 70,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 360,
                                      height: 70,
                                      decoration: BoxDecoration(
                                        color: Colors.white,
                                        boxShadow: [
                                          BoxShadow(
                                            color: Color(0x1E000000),
                                            blurRadius: 48,
                                            offset: Offset(0, 2),
                                            spreadRadius: 0,
                                          )
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 71,
                                    top: 15,
                                    child: Container(
                                      width: 220,
                                      height: 17,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 17,
                                              height: 17,
                                              child: Stack(children: [
                                              ,
                                              ]),
                                            ),
                                          ),
                                          Positioned(
                                            left: 202,
                                            top: 0,
                                            child: Container(
                                              width: 18,
                                              height: 17,
                                              child: Stack(children: [
                                              ,
                                              ]),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 30,
                            top: 0,
                            child: Container(
                              width: 313,
                              height: 27,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 5.87,
                                    child: Container(
                                      width: 15.89,
                                      height: 16.43,
                                      child: Stack(children: [
                                      ,
                                      ]),
                                    ),
                                  ),
                                  Positioned(
                                    left: 117.58,
                                    top: -4,
                                    child: SizedBox(
                                      width: 62.44,
                                      height: 30,
                                      child: Text(
                                        'Home',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Color(0xFF29292D),
                                          fontSize: 18,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w700,
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 311.38,
                                    top: 3.52,
                                    child: Container(
                                      width: 1.62,
                                      height: 19.96,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 8.22,
                                            child: Container(
                                              width: 1.62,
                                              height: 2.35,
                                              decoration: ShapeDecoration(
                                                shape: OvalBorder(
                                                  side: BorderSide(
                                                    width: 1,
                                                    strokeAlign: BorderSide.strokeAlignCenter,
                                                    color: Color(0xFF29292D),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 1.62,
                                              height: 2.35,
                                              decoration: ShapeDecoration(
                                                shape: OvalBorder(
                                                  side: BorderSide(
                                                    width: 1,
                                                    strokeAlign: BorderSide.strokeAlignCenter,
                                                    color: Color(0xFF29292D),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 17.61,
                                            child: Container(
                                              width: 1.62,
                                              height: 2.35,
                                              decoration: ShapeDecoration(
                                                shape: OvalBorder(
                                                  side: BorderSide(
                                                    width: 1,
                                                    strokeAlign: BorderSide.strokeAlignCenter,
                                                    color: Color(0xFF29292D),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 23,
                            top: 51,
                            child: Container(
                              width: 251,
                              height: 54,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  SizedBox(
                                    width: 251,
                                    child: Text(
                                      'Today’s Highlights',
                                      style: TextStyle(
                                        color: Color(0xFF29292D),
                                        fontSize: 22,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w500,
                                      ),
                                    ),
                                  ),
                                  const SizedBox(height: 4),
                                  SizedBox(
                                    width: 173.17,
                                    child: Text(
                                      'Hi, Emma Mabel!',
                                      style: TextStyle(
                                        color: Color(0xFF9696A4),
                                        fontSize: 12,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w400,
                                        letterSpacing: 1,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 6,
                            top: 105,
                            child: Container(
                              width: 328,
                              height: 118,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 328,
                                      height: 118,
                                      decoration: ShapeDecoration(
                                        color: Colors.white,
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 17,
                                    top: 73,
                                    child: Container(
                                      width: 160.60,
                                      height: 31.58,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 22.01,
                                            child: Container(
                                              width: 160.60,
                                              height: 9.57,
                                              decoration: ShapeDecoration(
                                                color: Color(0xFFF2F2F2),
                                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 22.01,
                                            child: Container(
                                              width: 84.12,
                                              height: 9.57,
                                              decoration: ShapeDecoration(
                                                color: Color(0xFF6266EA),
                                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: -1,
                                            child: SizedBox(
                                              width: 22.09,
                                              height: 18,
                                              child: Text(
                                                '67%',
                                                style: TextStyle(
                                                  color: Color(0xFF9696A4),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                  letterSpacing: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 17,
                                    top: 13,
                                    child: Container(
                                      width: 110,
                                      height: 46,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          SizedBox(
                                            width: 150,
                                            height: 27,
                                            child: Text(
                                              'Goal = 10,800',
                                              style: TextStyle(
                                                color: Color(0xFF29292D),
                                                fontSize: 14,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w500,
                                                letterSpacing: 1,
                                              ),
                                            ),
                                          ),
                                          const SizedBox(height: 4),
                                          SizedBox(
                                            width: 108.57,
                                            height: 18,
                                            child: Text(
                                              '7236 Steps',
                                              style: TextStyle(
                                                color: Color(0xFF9696A4),
                                                fontSize: 12,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w400,
                                                letterSpacing: 1,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 183,
                                    top: 14,
                                    child: Container(
                                      width: 145,
                                      height: 90,
                                      decoration: ShapeDecoration(
                                        image: DecorationImage(
                                          image: NetworkImage("https://via.placeholder.com/145x90"),
                                          fit: BoxFit.fill,
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 335,
                      height: 423.39,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 1,
                            top: 69,
                            child: Container(
                              width: 334,
                              height: 354.39,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 328,
                                      height: 86,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 328,
                                              height: 86,
                                              decoration: ShapeDecoration(
                                                color: Colors.white,
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(12),
                                                ),
                                                shadows: [
                                                  BoxShadow(
                                                    color: Color(0x0F000000),
                                                    blurRadius: 48,
                                                    offset: Offset(0, 2),
                                                    spreadRadius: 0,
                                                  )
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 14,
                                            top: 20,
                                            child: Container(
                                              width: 24.42,
                                              height: 35.61,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 13.86,
                                                    top: 4.73,
                                                    child: Container(
                                                      width: 7.30,
                                                      height: 14.51,
                                                      decoration: BoxDecoration(
                                                        image: DecorationImage(
                                                          image: NetworkImage("https://via.placeholder.com/7x15"),
                                                          fit: BoxFit.fill,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 0.49,
                                                    top: 0,
                                                    child: Container(
                                                      width: 15.91,
                                                      height: 22.85,
                                                      decoration: BoxDecoration(
                                                        image: DecorationImage(
                                                          image: NetworkImage("https://via.placeholder.com/16x23"),
                                                          fit: BoxFit.fill,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 53,
                                            top: 20,
                                            child: SizedBox(
                                              width: 150,
                                              height: 40,
                                              child: Text(
                                                'Heart Rate',
                                                style: TextStyle(
                                                  color: Color(0xFF29292D),
                                                  fontSize: 20,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 263,
                                            top: 28,
                                            child: SizedBox(
                                              width: 48,
                                              child: Text(
                                                'bpm',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Color(0xFF29292D),
                                                  fontSize: 16,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  letterSpacing: 1,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 246.61,
                                    top: 342.78,
                                    child: Container(
                                      width: 11.61,
                                      height: 11.61,
                                      child: Stack(children: [
                                      ,
                                      ]),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 130,
                                    child: Container(
                                      width: 328,
                                      height: 86,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 328,
                                              height: 86,
                                              decoration: ShapeDecoration(
                                                color: Colors.white,
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(12),
                                                ),
                                                shadows: [
                                                  BoxShadow(
                                                    color: Color(0x0F000000),
                                                    blurRadius: 48,
                                                    offset: Offset(0, 2),
                                                    spreadRadius: 0,
                                                  )
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 14,
                                            top: 20,
                                            child: Container(
                                              width: 24.42,
                                              height: 35.61,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 13.86,
                                                    top: 4.73,
                                                    child: Container(
                                                      width: 7.30,
                                                      height: 14.51,
                                                      decoration: BoxDecoration(
                                                        image: DecorationImage(
                                                          image: NetworkImage("https://via.placeholder.com/7x15"),
                                                          fit: BoxFit.fill,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 0.49,
                                                    top: 0,
                                                    child: Container(
                                                      width: 15.91,
                                                      height: 22.85,
                                                      decoration: BoxDecoration(
                                                        image: DecorationImage(
                                                          image: NetworkImage("https://via.placeholder.com/16x23"),
                                                          fit: BoxFit.fill,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 53,
                                            top: 25,
                                            child: SizedBox(
                                              width: 150,
                                              height: 28,
                                              child: Text(
                                                'Blood Pressure',
                                                style: TextStyle(
                                                  color: Color(0xFF29292D),
                                                  fontSize: 18,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 263,
                                            top: 22,
                                            child: SizedBox(
                                              width: 59,
                                              child: Text.rich(
                                                TextSpan(
                                                  children: [
                                                    TextSpan(
                                                      text: ' ',
                                                      style: TextStyle(
                                                        color: Color(0xFF29292D),
                                                        fontSize: 18,
                                                        fontFamily: 'Poppins',
                                                        fontWeight: FontWeight.w500,
                                                        letterSpacing: 1,
                                                      ),
                                                    ),
                                                    TextSpan(
                                                      text: 'bpm',
                                                      style: TextStyle(
                                                        color: Color(0xFF29292D),
                                                        fontSize: 20,
                                                        fontFamily: 'Poppins',
                                                        fontWeight: FontWeight.w500,
                                                        letterSpacing: 1,
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                                textAlign: TextAlign.center,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 129,
                                    child: Container(
                                      width: 328,
                                      height: 86,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 328,
                                              height: 86,
                                              decoration: ShapeDecoration(
                                                color: Colors.white,
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(12),
                                                ),
                                                shadows: [
                                                  BoxShadow(
                                                    color: Color(0x0F000000),
                                                    blurRadius: 48,
                                                    offset: Offset(0, 2),
                                                    spreadRadius: 0,
                                                  )
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 14,
                                            top: 20,
                                            child: Container(
                                              width: 308,
                                              height: 36,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 39,
                                                    top: 5,
                                                    child: SizedBox(
                                                      width: 150,
                                                      height: 28,
                                                      child: Text(
                                                        'Blood Pressure',
                                                        style: TextStyle(
                                                          color: Color(0xFF29292D),
                                                          fontSize: 18,
                                                          fontFamily: 'Poppins',
                                                          fontWeight: FontWeight.w400,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 249,
                                                    top: 5,
                                                    child: SizedBox(
                                                      width: 59,
                                                      child: Text(
                                                        'mmHg',
                                                        textAlign: TextAlign.center,
                                                        style: TextStyle(
                                                          color: Color(0xFF29292D),
                                                          fontSize: 16,
                                                          fontFamily: 'Poppins',
                                                          fontWeight: FontWeight.w500,
                                                          letterSpacing: 1,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 0,
                                                    top: 0,
                                                    child: Container(
                                                      width: 240,
                                                      height: 36,
                                                      child: Stack(
                                                        children: [
                                                          Positioned(
                                                            left: 181,
                                                            top: 9,
                                                            child: SizedBox(
                                                              width: 56,
                                                              height: 27,
                                                              child: Text(
                                                                '132/80',
                                                                textAlign: TextAlign.center,
                                                                style: TextStyle(
                                                                  color: Colors.black,
                                                                  fontSize: 20,
                                                                  fontFamily: 'Poppins',
                                                                  fontWeight: FontWeight.w600,
                                                                  letterSpacing: 1,
                                                                ),
                                                              ),
                                                            ),
                                                          ),
                                                          Positioned(
                                                            left: 0,
                                                            top: 0,
                                                            child: Container(
                                                              width: 24.42,
                                                              height: 35.61,
                                                              child: Stack(
                                                                children: [
                                                                  Positioned(
                                                                    left: 13.86,
                                                                    top: 4.73,
                                                                    child: Container(
                                                                      width: 7.30,
                                                                      height: 14.51,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/7x15"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                  Positioned(
                                                                    left: 0.49,
                                                                    top: 0,
                                                                    child: Container(
                                                                      width: 15.91,
                                                                      height: 22.85,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/16x23"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                ],
                                                              ),
                                                            ),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 6,
                                    top: 257,
                                    child: Container(
                                      width: 328,
                                      height: 86,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 8,
                                            top: 25,
                                            child: Container(
                                              width: 308,
                                              height: 37.21,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 39,
                                                    top: 5,
                                                    child: SizedBox(
                                                      width: 150,
                                                      height: 28,
                                                      child: Text(
                                                        'Walking',
                                                        style: TextStyle(
                                                          color: Color(0xFF29292D),
                                                          fontSize: 18,
                                                          fontFamily: 'Poppins',
                                                          fontWeight: FontWeight.w400,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 249,
                                                    top: 5,
                                                    child: SizedBox(
                                                      width: 59,
                                                      child: Text(
                                                        'Steps',
                                                        textAlign: TextAlign.center,
                                                        style: TextStyle(
                                                          color: Color(0xFF29292D),
                                                          fontSize: 16,
                                                          fontFamily: 'Poppins',
                                                          fontWeight: FontWeight.w500,
                                                          letterSpacing: 1,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 0,
                                                    top: 0,
                                                    child: Container(
                                                      width: 240,
                                                      height: 37.21,
                                                      child: Stack(
                                                        children: [
                                                          Positioned(
                                                            left: 181,
                                                            top: 9,
                                                            child: SizedBox(
                                                              width: 56,
                                                              height: 27,
                                                              child: Text(
                                                                '7326',
                                                                textAlign: TextAlign.center,
                                                                style: TextStyle(
                                                                  color: Colors.black,
                                                                  fontSize: 20,
                                                                  fontFamily: 'Poppins',
                                                                  fontWeight: FontWeight.w600,
                                                                  letterSpacing: 1,
                                                                ),
                                                              ),
                                                            ),
                                                          ),
                                                          Positioned(
                                                            left: 0,
                                                            top: 0,
                                                            child: Container(
                                                              width: 30.42,
                                                              height: 37.21,
                                                              child: Stack(
                                                                children: [
                                                                  Positioned(
                                                                    left: 6.52,
                                                                    top: -0,
                                                                    child: Container(
                                                                      width: 23.90,
                                                                      height: 26.05,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/24x26"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                  Positioned(
                                                                    left: 13.04,
                                                                    top: 9.66,
                                                                    child: Container(
                                                                      width: 6.52,
                                                                      height: 7.44,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/7x7"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                  Positioned(
                                                                    left: 16.30,
                                                                    top: 26.05,
                                                                    child: Container(
                                                                      width: 7.60,
                                                                      height: 8.68,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/8x9"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                  Positioned(
                                                                    left: -0,
                                                                    top: 26.05,
                                                                    child: Container(
                                                                      width: 9.78,
                                                                      height: 11.16,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/10x11"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                  Positioned(
                                                                    left: -0,
                                                                    top: 12.42,
                                                                    child: Container(
                                                                      width: 6.52,
                                                                      height: 7.44,
                                                                      decoration: BoxDecoration(
                                                                        image: DecorationImage(
                                                                          image: NetworkImage("https://via.placeholder.com/7x7"),
                                                                          fit: BoxFit.fill,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ),
                                                                ],
                                                              ),
                                                            ),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 0,
                            top: 0,
                            child: Container(
                              width: 333,
                              height: 50,
                              decoration: ShapeDecoration(
                                color: Color(0xFF6266EA),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                              ),
                            ),
                          ),
                          Positioned(
                            left: 196,
                            top: 98,
                            child: Container(
                              width: 59,
                              height: 26,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 9,
                                    top: 3,
                                    child: SizedBox(
                                      width: 41,
                                      height: 23,
                                      child: Text(
                                        '80',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Colors.black,
                                          fontSize: 20,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w600,
                                          letterSpacing: 1,
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}